manifest:
    remotes:
      - name: zmkfirmware
        url-base: https://github.com/zmkfirmware
      - name: xzebra
        url-base: https://github.com/tony-soft-dev
    projects:
      - name: zmk
        remote: zmkfirmware
        revision: main   
        import: app/west.yml
    self:
      path: config
